config: 1.0
## created by zvicraft


none-player: "&cOnly a player can do that command."
none-target: "&cYou need a player to do this command."
none-need-args: "&7You don't need a bigger argument than that in your command."
none-alive: "&cThis player does not exist or is not on the server."
reload: "&aThe plugin has been updated successfully."
player-same: "&cYou can't do this to yourself!"

#error
MUST-BE-PLAYER-ERROR: "&cOnly a player can execute this command!"


#discord
#WEBHOOK_URL_PLAYER: "" #url
#WEBHOOK_URL_BUGS: "" #url
#GUI-icon: "" #url
ReportCMD: "/" #prefix

#GUI


#bot discord
TOKEN-INVADE: "ERROR: Provided bot token is invalid!"

TOKEN: ""
PLAYER-CHANNEL: #Id
BUGS-CHANNEL: #Id
WSH: "" #Text
GILD-ID: #Id

Channel-server: "" #FORMAT: "your_name_plugin:channel" from MCReport spigot version