name: MCreported
main: ml.zvicraft.dev.mcreported.MCreported_Plugin
description: reports systems
version: '2.0.1'
api-version: 1.18
commands:
   report:
     description: open gui reports
     usage: /<command>

   reloadrmc:
      description: reload configs
      usage: /<command>

   reports:
     description: show all reports
     usage: /<command>

   reportscancel:
       description: cancel 1 reports
       usage: /<command>

   reportscancelall:
     description:
     usage: /<command>